### ISSUE TITLE
How can I detect that an element is moved?

### ISSUE THREAD

**Issue by Sweeper777** [hironytic/Diffitic#4]
For these two sequences:

        let left = ["A", "B", "C", "D"]
        let right = ["B", "C", "A", "D"]

The output is:

```
(.deleted, 0, 1, 0, 0)
(.identical, 1, 2, 0, 2)
(.inserted, 3, 0, 2, 1)
(.identical, 3, 1, 3, 1)
```

I want to write a method that takes the above output as input, and returns something like this:

```
[(0, 2)]
```

Meaning that the element at 0 is moved to index 2. 

or:

```
[(1, 0), (2, 1)]
```

How should I do this?

Note that I understand elements are not necessarily "moved", but I just want to do it this way.

**Comment by hironytic** [comment]
@Sweeper777 I'm sorry but you cannot. In my understanding, Wu's algorithm, on which this module is based, is not suitable for detecting "moved". Other algorithm such as Heckel's can detect it. For example, [DifferenceKit](https://github.com/ra1028/DifferenceKit) is based on Heckel's algorithm 🙂

**Comment by Sweeper777** [comment]
I see. Thanks for suggesting DifferenceKit. I'll try that.
